---
version: 2
jobs:
  sync_drupalorg:
    docker:
      - image: nicksantamaria/utilities
    working_directory: /data
    environment:
      GIT_MIRROR_URL: nickurbits@git.drupal.org:sandbox/nickurbits/2923717.git
    steps:
      - checkout
      - name: Add drupal.org git remote
        command: git remote add drupal "${GIT_MIRROR_URL}"
      - name: Push to drupal.org git remote
        command: git push --tags drupal "${CIRCLE_BRANCH}"

workflows:
  version: 2
  sync:
    jobs:
      - sync_drupalorg
    filters:
      tags:
        only: /.*/
      branches:
        only: /[7-9].x-.*/
